# Spectrogram generation options

[paths]
#piezo_audio_paths = ["data/Bl122.flac", 
#            "data/Li145.flac",
#            "data/Or61.flac",
#            "data/Ti81.flac"]

#label_paths = ["data/Bl122_hand_dorian.txt",
#            "data/Li145.txt",
#            "data/Or61.txt",
#            "data/Ti81.txt"]


piezo_audio_paths = ["data/NB_Ch3.flac"]
label_paths = ['data/NB_Ch3.txt']

csv_write_path = "data/NB_Ch3.csv"
edge_write_dir = "edge/"
img_write_dir = "spec/"

[spec_options]